apiVersion: v1
kind: Service
metadata:
  name: grafana-node-port
  namespace: observability
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: kube-prom-stack
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31928
