apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-webhook
  namespace: observability
data:
  webhookURL: "aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA3R1Q0MEVIUEYvQjA3SDhNMjJRM0IvRzdGZVJOT1M4SU9EZXlGbVpyZ1ZqNzg5"
