apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    labels:
      app: sensors
      tier: prometheus
    name: prometheus-sensors
    namespace: observability
  spec:
    alerting:
      alertmanagers:
      - name: sensors-alertmanager
        namespace: observability
        port: http-web
    enableAdminAPI: false
    evaluationInterval: 30s
    externalUrl: http://sensors-prometheus.observability:9099
    hostNetwork: false
    image: quay.io/prometheus/prometheus:v2.42.0
    listenLocal: false
    logFormat: logfmt
    logLevel: info
    paused: false
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    portName: http-web
    probeNamespaceSelector: {}
    probeSelector: {}
    replicas: 1
    retention: 10d
    routePrefix: /
    ruleNamespaceSelector: {}
    ruleSelector:
      matchLabels:
        app: sensors
    scrapeInterval: 30s
    securityContext:
      fsGroup: 2000
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: sensors-prometheus
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector:
      matchLabels:
        app: sensors
    shards: 1
    version: v2.42.0
    walCompression: true
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2024-08-15T09:46:01Z"
      observedGeneration: 1
      status: "True"
      type: Available
    - lastTransitionTime: "2024-08-15T09:45:38Z"
      observedGeneration: 1
      status: "True"
      type: Reconciled
    paused: false
    replicas: 1
    shardStatuses:
    - availableReplicas: 1
      replicas: 1
      shardID: "0"
      unavailableReplicas: 0
      updatedReplicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
