apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-port
  namespace: observability
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: prometheus-kube-prom-stack-kube-prome-prometheus-0
  ports:
    - protocol: TCP
      port: 909
      targetPort: 9090
      nodePort: 31927
