apiVersion: v1
kind: Service
metadata:
  name: be-flask-sv
  labels:
    app: sensors
    tier: be
    type: service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 31926
      protocol: TCP
      name: be-port
  selector:
    app: sensors
    tier: be
    type: flask
