apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-ss
  labels:
    app: sensors
    tier: db
    type: stateful-set
spec:
  selector:
    matchLabels:
      app: sensors
      tier: db
      type: mongo
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: sensors
        tier: db
        type: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          ports:
           - containerPort: 27017
          volumeMounts:
           - name: mongo-storage
             mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: ["ReadWriteMany"]
        storageClassName: ""
        resources:
          requests:
            storage: 1Gi
