apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: sensors
    tier: db
    type: service
spec:
  ports:
    - port: 27017
      name: mongodb
  clusterIP: None
  selector:
    app: sensors
    tier: db
    type: mongo
