{
 "title": "Sensors Dashboard",
 "description": "Dashboard for my thesis sensors application",
 "tags": [ "sensors" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(exported_endpoint) (sensors_http_requests_count_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sensors_http_requests_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A + $B", "type": "math" },
    {
     "expr": "sum(sensors_http_error_count_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sensors_http_error_arguments_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "HTTP requests over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(exported_endpoint) (rate(sensors_http_requests_count_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP errors over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by(type) (rate(sensors_http_error_arguments_count_total[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(status_code) (rate(sensors_http_error_count_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP requests duration histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  }
 ]
}